# Generated by Django 6.0.1 on 2026-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage'], name='core_deal_stage_c7f31c_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_date'], name='core_deal_expecte_814359_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='core_task_assigne_5bfa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='core_task_due_dat_d0a0d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='unique_owner_deal_title'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'completed', 'overdue'])), name='task_status_valid'),
        ),
    ]
