# Generated by Django 6.0.1 on 2026-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deal_core_deal_stage_c7f31c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
